import { createSlice } from '@reduxjs/toolkit';



const initialState = {
  accessToken: null,
};

// Create a Redux slice for the game
const accessTokenSlice = createSlice({
  name: 'accessToken',
  initialState,
  reducers: {
    setAccessToken: (state, action) => {
      state.accessToken = action.payload.accessToken;
    },
  },
});

// Export actions generated by createSlice
export const {
  setAccessToken,

} = accessTokenSlice.actions;

// Export the reducer
export default accessTokenSlice.reducer;
