import { createSlice } from '@reduxjs/toolkit';

const initialState: {
  user: Record<string, any> | null,
  authanticated: boolean,
  accessToken: string | null,
} = {
  user: null,
  authanticated: false,
  accessToken: null,
};

// Create a Redux slice for the game
const accessTokenSlice = createSlice({
  name: 'loggedUser',
  initialState,
  reducers: {
    setAccessToken: (state, action) => {
      state.accessToken = action.payload.accessToken;
    },
    setUser: (state, action) => {
      if (action.payload.user) {
        state.user = [...action.payload.user];
        state.authanticated = true;
      } else {
        state.user = null;
        state.authanticated = false;
      }
    },
  },
});

// Export actions generated by createSlice
export const {
  setAccessToken,
  setUser

} = accessTokenSlice.actions;

// Export the reducer
export default accessTokenSlice.reducer;
